const SELECTED: any[] = [
  {
    "id": "printful-home-living-1",
    "sku": "PFL-HOME-TOTE-HYGGE",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Hygge Market Tote",
    "category": "Living",
    "supplierPriceUsd": 7.1,
    "suggestedRetailUsd": 22.5,
    "image": "https://images.unsplash.com/photo-1590874103328-eac38a67478e?auto=format&fit=crop&w=800&q=80",
    "matchType": "tote",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-2",
    "sku": "PFL-HOME-TOTE-KITCHEN",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Scandi Kitchen Tote",
    "category": "Kitchen",
    "supplierPriceUsd": 7.1,
    "suggestedRetailUsd": 21.9,
    "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80",
    "matchType": "tote",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-3",
    "sku": "PFL-HOME-TOTE-LINEN",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Linen Life Canvas Tote",
    "category": "Living",
    "supplierPriceUsd": 7.1,
    "suggestedRetailUsd": 23.5,
    "image": "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=80",
    "matchType": "tote",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-4",
    "sku": "PFL-HOME-POSTER-LINE",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Scandi Line Art Poster",
    "category": "Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 24.9,
    "image": "https://images.unsplash.com/photo-1513519245088-0e12902e35a6?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-5",
    "sku": "PFL-HOME-POSTER-FOREST",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Nordic Forest Wall Poster",
    "category": "Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 23.9,
    "image": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-6",
    "sku": "PFL-HOME-POSTER-BOTANICA",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Minimal Botanica Poster",
    "category": "Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 22.9,
    "image": "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-7",
    "sku": "PFL-HOME-MUG-ACCENT",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Accent Mug \u2014 Nordic Home",
    "category": "Home Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 19.9,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-8",
    "sku": "PFL-HOME-MUG-SUNDAY",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Sunday Slow Coffee Mug",
    "category": "Kitchen",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 18.9,
    "image": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-9",
    "sku": "PFL-HOME-MUG-CABIN",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Cosy Cabin Ceramic Mug",
    "category": "Living",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 17.9,
    "image": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-10",
    "sku": "PFL-HOME-POSTER-RECIPE",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Recipe Notes Kitchen Poster",
    "category": "Kitchen",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 21.5,
    "image": "https://images.unsplash.com/photo-1556911220-bff31c9870c0?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-11",
    "sku": "PFL-HOME-TOTE-FIKA",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Fika Time Tote",
    "category": "Living",
    "supplierPriceUsd": 7.1,
    "suggestedRetailUsd": 20.9,
    "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80",
    "matchType": "tote",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-12",
    "sku": "PFL-HOME-MUG-LIGHT",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Warm Light Quote Mug",
    "category": "Decor",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 16.9,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-13",
    "sku": "PFL-HOME-POSTER-LAGOM",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Lagom Living Poster",
    "category": "Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 23.5,
    "image": "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-14",
    "sku": "PFL-HOME-MUG-MORNING",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Morning Light Coffee Mug",
    "category": "Kitchen",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 17.5,
    "image": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-15",
    "sku": "PFL-HOME-TOTE-MARKET",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Market Day Linen Tote",
    "category": "Living",
    "supplierPriceUsd": 7.1,
    "suggestedRetailUsd": 22.9,
    "image": "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=80",
    "matchType": "tote",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-16",
    "sku": "PFL-HOME-POSTER-FIRE",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Fireside Quote Poster",
    "category": "Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 23.9,
    "image": "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-17",
    "sku": "PFL-HOME-TOTE-SLOW",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Slow Sunday Market Tote",
    "category": "Living",
    "supplierPriceUsd": 7.1,
    "suggestedRetailUsd": 22.5,
    "image": "https://images.unsplash.com/photo-1590874103328-eac38a67478e?auto=format&fit=crop&w=800&q=80",
    "matchType": "tote",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-18",
    "sku": "PFL-HOME-MUG-CINNAMON",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Cinnamon Morning Mug",
    "category": "Kitchen",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 18.5,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-19",
    "sku": "PFL-HOME-POSTER-NEST",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Nordic Nest Wall Poster",
    "category": "Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 24.5,
    "image": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-20",
    "sku": "PFL-HOME-TOTE-BREAD",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Bread Day Kitchen Tote",
    "category": "Kitchen",
    "supplierPriceUsd": 7.1,
    "suggestedRetailUsd": 21.9,
    "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80",
    "matchType": "tote",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-21",
    "sku": "PFL-HOME-MUG-CANDLE",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Candle Hour Ceramic Mug",
    "category": "Living",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 17.9,
    "image": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-22",
    "sku": "PFL-HOME-POSTER-GEO",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Soft Geometry Poster",
    "category": "Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 22.9,
    "image": "https://images.unsplash.com/photo-1513519245088-0e12902e35a6?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-23",
    "sku": "PFL-HOME-TOTE-LAUNDRY",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Laundry Day Linen Tote",
    "category": "Living",
    "supplierPriceUsd": 7.1,
    "suggestedRetailUsd": 20.9,
    "image": "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=80",
    "matchType": "tote",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-24",
    "sku": "PFL-HOME-MUG-COCOA",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Night Cocoa Mug",
    "category": "Kitchen",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 16.9,
    "image": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-25",
    "sku": "PFL-HOME-POSTER-WINDOW",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Window Light Botanica Poster",
    "category": "Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 25.5,
    "image": "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-home-living-26",
    "sku": "PFL-HOME-POSTER-SOFTGEO",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Soft Geometry Home Poster",
    "category": "Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 23.5,
    "image": "https://images.unsplash.com/photo-1513519245088-0e12902e35a6?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-27",
    "sku": "PFL-HOME-TOTE-MORNING",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Market Morning Linen Tote",
    "category": "Living",
    "supplierPriceUsd": 7.1,
    "suggestedRetailUsd": 22.5,
    "image": "https://images.unsplash.com/photo-1590874103328-eac38a67478e?auto=format&fit=crop&w=800&q=80",
    "matchType": "tote",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-28",
    "sku": "PFL-HOME-MUG-QUIET",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Quiet Kitchen Coffee Mug",
    "category": "Kitchen",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 18.5,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-29",
    "sku": "PFL-HOME-POSTER-WINDOW2",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Fjord Window Wall Poster",
    "category": "Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 24.5,
    "image": "https://images.unsplash.com/photo-1513519245088-0e12902e35a6?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-30",
    "sku": "PFL-HOME-TOTE-HERB",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Herb Garden Canvas Tote",
    "category": "Kitchen",
    "supplierPriceUsd": 7.1,
    "suggestedRetailUsd": 21.5,
    "image": "https://images.unsplash.com/photo-1590874103328-eac38a67478e?auto=format&fit=crop&w=800&q=80",
    "matchType": "tote",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-31",
    "sku": "PFL-HOME-MUG-TEA",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Evening Tea Ceramic Mug",
    "category": "Kitchen",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 17.5,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-32",
    "sku": "PFL-HOME-POSTER-SOFTLINE",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Soft Line Art Poster",
    "category": "Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 22.5,
    "image": "https://images.unsplash.com/photo-1513519245088-0e12902e35a6?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-33",
    "sku": "PFL-HOME-TOTE-LAUNDRY2",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Laundry Soft Day Tote",
    "category": "Living",
    "supplierPriceUsd": 7.1,
    "suggestedRetailUsd": 20.5,
    "image": "https://images.unsplash.com/photo-1590874103328-eac38a67478e?auto=format&fit=crop&w=800&q=80",
    "matchType": "tote",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-34",
    "sku": "PFL-HOME-MUG-HEARTH",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Hearth Side Coffee Mug",
    "category": "Living",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 19.5,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-35",
    "sku": "PFL-HOME-POSTER-PINE",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Pine Shadow Wall Poster",
    "category": "Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 25.5,
    "image": "https://images.unsplash.com/photo-1513519245088-0e12902e35a6?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-36",
    "sku": "PFL-HOME-TOTE-BAKERY",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Bakery Run Canvas Tote",
    "category": "Kitchen",
    "supplierPriceUsd": 7.1,
    "suggestedRetailUsd": 23.5,
    "image": "https://images.unsplash.com/photo-1590874103328-eac38a67478e?auto=format&fit=crop&w=800&q=80",
    "matchType": "tote",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-37",
    "sku": "PFL-HOME-MUG-RAINY",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Rainy Afternoon Mug",
    "category": "Living",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 16.5,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-38",
    "sku": "PFL-HOME-POSTER-ARCH",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Soft Arch Decor Poster",
    "category": "Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 21.5,
    "image": "https://images.unsplash.com/photo-1513519245088-0e12902e35a6?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-39",
    "sku": "PFL-HOME-TOTE-CLOSET",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Closet Day Canvas Tote",
    "category": "Living",
    "supplierPriceUsd": 7.1,
    "suggestedRetailUsd": 22.9,
    "image": "https://images.unsplash.com/photo-1590874103328-eac38a67478e?auto=format&fit=crop&w=800&q=80",
    "matchType": "tote",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-40",
    "sku": "PFL-HOME-MUG-PAPER",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Sunday Paper Coffee Mug",
    "category": "Kitchen",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 18.9,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-41",
    "sku": "PFL-HOME-POSTER-OAK",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Pale Oak Wall Poster",
    "category": "Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 26.5,
    "image": "https://images.unsplash.com/photo-1513519245088-0e12902e35a6?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-42",
    "sku": "PFL-HOME-TOTE-FARMERS",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Farmers Market Soft Tote",
    "category": "Living",
    "supplierPriceUsd": 7.1,
    "suggestedRetailUsd": 24.5,
    "image": "https://images.unsplash.com/photo-1590874103328-eac38a67478e?auto=format&fit=crop&w=800&q=80",
    "matchType": "tote",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-43",
    "sku": "PFL-HOME-MUG-SOFTLIGHT",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Soft Light Ceramic Mug",
    "category": "Living",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 17.9,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-44",
    "sku": "PFL-HOME-POSTER-COAST",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Coastal Calm Poster",
    "category": "Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 23.9,
    "image": "https://images.unsplash.com/photo-1513519245088-0e12902e35a6?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-45",
    "sku": "PFL-HOME-TOTE-LINEN2",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Linen Closet Canvas Tote",
    "category": "Living",
    "supplierPriceUsd": 7.1,
    "suggestedRetailUsd": 21.9,
    "image": "https://images.unsplash.com/photo-1590874103328-eac38a67478e?auto=format&fit=crop&w=800&q=80",
    "matchType": "tote",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-46",
    "sku": "PFL-HOME-MUG-SHELF",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Night Shelf Coffee Mug",
    "category": "Kitchen",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 19.9,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-47",
    "sku": "PFL-HOME-POSTER-CLAY",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Warm Clay Wall Poster",
    "category": "Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 22.9,
    "image": "https://images.unsplash.com/photo-1513519245088-0e12902e35a6?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-48",
    "sku": "PFL-HOME-TOTE-ENTRY",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Entryway Soft Tote",
    "category": "Living",
    "supplierPriceUsd": 7.1,
    "suggestedRetailUsd": 23.9,
    "image": "https://images.unsplash.com/photo-1590874103328-eac38a67478e?auto=format&fit=crop&w=800&q=80",
    "matchType": "tote",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-49",
    "sku": "PFL-HOME-MUG-STEAM",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Morning Steam Mug",
    "category": "Kitchen",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 16.9,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-home-living-50",
    "sku": "PFL-HOME-POSTER-HORIZON",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Soft Horizon Home Poster",
    "category": "Decor",
    "supplierPriceUsd": 7.5,
    "suggestedRetailUsd": 25.9,
    "image": "https://images.unsplash.com/photo-1513519245088-0e12902e35a6?auto=format&fit=crop&w=800&q=80",
    "matchType": "poster",
    "sector": "home living",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  }
];
const SECTOR_ALIASES: Record<string, string> = {
  "beauty": "beauty",
  "perfume": "beauty",
  "perfumes": "beauty",
  "skincare": "beauty",
  "toys": "toys",
  "kids": "toys",
  "kid": "toys",
  "children": "toys",
  "electronics": "electronics",
  "tech": "electronics",
  "technology": "electronics",
  "pet supplies": "pet supplies",
  "pets": "pet supplies",
  "pet": "pet supplies",
  "home living": "home living",
  "home": "home living",
  "living": "home living",
  "fitness": "fitness",
  "outdoor": "fitness",
  "sports": "fitness",
  "solar energy": "solar energy",
  "energy": "solar energy",
  "solar": "solar energy",
  "car accessories": "car accessories",
  "car": "car accessories",
  "auto": "car accessories",
  "automotive": "car accessories"
};
function money(value: unknown) {
  const amount = Number(value);
  return Number.isFinite(amount) && amount > 0 ? Math.round(amount * 100) / 100 : 0;
}
function resolveSector(raw: string) {
  const key = String(raw || "").toLowerCase().trim();
  if (!key) return SELECTED[0]?.sector || "beauty";
  if (SECTOR_ALIASES[key]) return SECTOR_ALIASES[key];
  for (const [alias, sector] of Object.entries(SECTOR_ALIASES)) {
    if (key.includes(alias) || alias.includes(key)) return sector;
  }
  return key;
}
function curated(sector: string) {
  return SELECTED
    .filter((p) => !p.sector || String(p.sector).toLowerCase() === sector)
    .map((p, i) => ({
      id: String(p.id || `printful-selected-${i}`),
      sku: String(p.sku || ""),
      supplier: "Printful",
      provider: "printful",
      name: String(p.name || "Printful product"),
      category: String(p.category || sector),
      supplierPriceUsd: money(p.supplierPriceUsd) || money(p.suggestedRetailUsd),
      suggestedRetailUsd: money(p.suggestedRetailUsd) || money(p.supplierPriceUsd),
      image: String(p.image || ""),
      sector: String(p.sector || sector),
    }))
    .filter((p) => p.suggestedRetailUsd > 0 && p.name);
}
export async function onRequestGet(context: any) {
  const url = new URL(context.request.url);
  const wanted = url.searchParams.get("q") || url.searchParams.get("sector") || "";
  const defaultSector = String(SELECTED[0]?.sector || "beauty");
  const sector = resolveSector(wanted || defaultSector);
  const headers = { "access-control-allow-origin": "*", "cache-control": "public, max-age=60" };
  const products = curated(sector).slice(0, 50);
  return Response.json(
    { ok: true, supplier: "printful", sector, query: sector, products, count: products.length, source: "printful-selected-primary", markets: ["NO", "EU", "PE"] },
    { status: products.length ? 200 : 503, headers }
  );
}
